local cp = require('theme-nvim.palletes.frappe')
return {
	CmpItemAbbr = { fg = cp.overlay2 },
	CmpItemAbbrDeprecated = { fg = cp.overlay0, style = { 'strikethrough' } },
	CmpItemKind = { fg = cp.blue_0 },
	CmpItemMenu = { fg = cp.text },
	CmpItemAbbrMatch = { fg = cp.blue_1, style = { 'bold' } },
	CmpItemAbbrMatchFuzzy = { fg = cp.blue_0 },

	-- kind support
	CmpItemKindSnippet = { fg = cp.pink_1 },
	CmpItemKindKeyword = { fg = cp.red },
	CmpItemKindText = { fg = cp.teal },
	CmpItemKindMethod = { fg = cp.blue_0 },
	CmpItemKindConstructor = { fg = cp.blue_0 },
	CmpItemKindFunction = { fg = cp.orange },
	CmpItemKindFolder = { fg = cp.gold },
	CmpItemKindModule = { fg = cp.blue_0 },
	CmpItemKindConstant = { fg = cp.peach },
	CmpItemKindField = { fg = cp.green },
	CmpItemKindProperty = { fg = cp.green },
	CmpItemKindEnum = { fg = cp.green },
	CmpItemKindUnit = { fg = cp.green },
	CmpItemKindClass = { fg = cp.yellow },
	CmpItemKindVariable = { fg = cp.whiteSmoke },
	CmpItemKindFile = { fg = cp.green_1 },
	CmpItemKindInterface = { fg = cp.yellow },
	CmpItemKindColor = { fg = cp.red },
	CmpItemKindReference = { fg = cp.red },
	CmpItemKindEnumMember = { fg = cp.red },
	CmpItemKindStruct = { fg = cp.blue_0 },
	CmpItemKindValue = { fg = cp.peach },
	CmpItemKindEvent = { fg = cp.blue_0 },
	CmpItemKindOperator = { fg = cp.blue_0 },
	CmpItemKindTypeParameter = { fg = cp.blue_0 },
	CmpItemKindCopilot = { fg = cp.teal_1 },
	CmpItemKindCodeium = { fg = cp.teal_1 },
}
